---
- name: make the ssh group
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - ssh

- name: making new user
  user:
    name: "{{ user.name }}"
    home: "{{ user.home }}"
    groups: docker,ssh
    shell: "{{ user.shell }}"
    state: present

- name: create a user ssh_key
  user:
    name: "{{ user.name }}"
    generate_ssh_key: yes
    ssh_key_type: "{{ user.keytype }}"
    ssh_key_file: ".ssh/{{ user.name }}"

- name: set up key access
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ lookup('file', user.pub) }}"
